// USERNAME INPUT
export const SUBMIT_USERNAME_SUCCESS = 'SUBMIT_USERNAME_SUCCESS';
export const SUBMIT_USERNAME_FAILURE = 'SUBMIT_USERNAME_FAILURE';
export const USERNAME_ERROR = 'USERNAME_ERROR';
export const CLEAR_USERNAME = 'CLEAR_USERNAME';

// USER REPOS
export const REPOS_FETCH_SUCCESS = 'REPOS_FETCH_SUCCESS';
export const REPOS_FETCH_FAILURE = 'REPOS_FETCH_FAILRUE';
export const REPOS_ARE_LOADING = 'REPOS_ARE_LOADING';
export const REPOS_LOAD_SUCCESS = 'REPOS_LOAD_SUCCESS';
export const REPOS_LOAD_FAILURE = 'REPOS_LOAD_FAILURE';

// USER PULL REQUESTS
export const PRS_FETCH_SUCCESS = 'PRS_FETCH_SUCCESS';
export const PRS_FETCH_FAILURE = 'PRS_FETCH_FAILURE';
export const PRS_ARE_LOADING = 'PRS_ARE_LOADING';
export const PRS_LOAD_SUCCESS = 'PRS_LOAD_SUCCESS';
export const PRS_LOAD_FAILURE = 'PRS_LOAD_FAILURE';
